import React, { useEffect, useState } from "react";
import { useSelector } from "react-redux";
import GridModal from "./GridModal";
import useGetDBTables from "../../CustomHooks/useGetDBTables";
import { useLocation } from "react-router-dom";
import { SimpleInputField } from "../Common/SimpleInputField";
import { SimpleSelectField } from "../Common/SimpleSelectField";
import { SimpleDatePickerField } from "../Common/SimpleDatePickerField";

export default function VerbalCommTable({
  verbalCommGridData,
  deleteTableRows,
  handleGridSelectChange,
  addTableRows,
  handleGridDateChange,
  handleGridFieldChange,
  gridRowsFinalSubmit,
  selectJson,
  lockStatus,
  editTableRows,
  gridFieldTempState,
  validationSchema,
}) {
  VerbalCommTable.displayName = "VerbalCommTable";

  const [dataIndex, setDataIndex] = useState();
  const [validationErrors, setValidationErrors] = useState({});

  const [operationValue, setOperationValue] = useState("");

  const [modalShow, setModalShow] = useState(false);

  const [isTouched, setIsTouched] = useState({});

  const { getGridJson, convertToCase } = useGetDBTables();

  const [statusValues, setstatusValues] = useState([]);
  const [communicationTypeValues, setcommunicationTypeValues] = useState([]);
  const [purposeOutreachValues, setpurposeOutreachValues] = useState([]);
  const [mailingMethodValues, setmailingMethodValues] = useState([]);
  const [communicationWithValues, setcommunicationWithValues] = useState([]);
  const [memberProviderListValues, setmemberProviderListValues] = useState([]);

  let prop = useLocation();
  const masterAngPurposeOfOutreachSelector = useSelector(
    (state) => state?.masterAngPurposeOfOutreach,
  );
  const masterAngCommunicationTypeSelector = useSelector(
    (state) => state?.masterAngCommType,
  );
  const masterAngStatusSelector = useSelector(
    (state) => state?.masterAngStatus,
  );

  const masterAngMailingMethodSelector = useSelector(
    (state) => state?.masterAngMailingMethod,
  );
  const masterAngCommunicationWithSelector = useSelector(
    (state) => state?.masterAngCommWith,
  );
  const masterAngMemberProviderListSelector = useSelector(
    (state) => state?.masterAngMemberProviderList,
  );
 
useEffect(() => {
    const kvMapper = (e) => ({
      label: convertToCase(e),
      value: convertToCase(e),
    });
    const purposeOfOutreach = masterAngPurposeOfOutreachSelector?.[0] || [];
    setpurposeOutreachValues(
      purposeOfOutreach.map((e) => e.Purpose_of_Outreach).map(kvMapper),
    );
    const communicationType = masterAngCommunicationTypeSelector?.[0] || [];
    setcommunicationTypeValues(
        communicationType.map((e) => e.Communication_Type).map(kvMapper),
    );
    const status =masterAngStatusSelector?.[0] || [];
    setstatusValues(
      status.map((e) => e.Status).map(kvMapper),
    );

    // const mailingMethod = masterAngMailingMethodSelector?.[0] || [];
    // setletterTriggerTypeValues(
    //     mailingMethod.map((e) => e.Doc_Needed).map(kvMapper),
    // );
    const communicationWith = masterAngCommunicationWithSelector?.[0] || [];
    setcommunicationWithValues(
        communicationWith.map((e) => e.Communication_With).map(kvMapper),
    );
    // const memberProviderList =masterAngMemberProviderListSelector?.[0] || [];
    // setnameDescriptionValues(
    //     memberProviderList.map((e) => e.Needed_By).map(kvMapper),
    // );
    
}, []);
  

  const tableFields = [
    "Outreach_Attempt",
    "Entry_Date_Time",
    "Communication_Type",
    "Communication_With",
    "Call_Logs",
    "Purpose_of_Outreach",
    "Status",
    "Outreach_Date_Time",
    "Generated By"
  ];



  const renderSimpleInputField = (name, label, maxLength, index) => {
    return (
      <div className="col-xs-6 col-md-3">
        <SimpleInputField
          name={name}
          label={label}
          maxLength={maxLength}
          data={gridFieldTempState}
          validationErrors={validationErrors}
          onChange={(event) =>
            handleGridFieldChange(
              index,
              event,
              VerbalCommTable.displayName,
            )
          }
        //   disabled={
        //     (prop.state.formView === "DashboardView" &&
        //       (prop.state.stageName === "Redirect Review" ||
        //         prop.state.stageName === "Effectuate" ||
        //         prop.state.stageName === "Pending Effectuate" ||   
        //         prop.state.stageName === "Case Completed" ||
        //         prop.state.stageName === "CaseArchived"))   
        //   }
        />
      </div>
    );
  };
  const renderSimpleSelectField = (name, label, options, index) => {
    return (
      <div className="col-xs-6 col-md-3">
        <SimpleSelectField
          name={name}
          label={label}
          options={options}
          data={gridFieldTempState}
          validationErrors={validationErrors}
          onChange={(selectValue, event) =>
            handleGridSelectChange(
              index,
              selectValue,
              event,
              VerbalCommTable.displayName,
            )
          }
        //   disabled={
        //         prop.state.formView === "DashboardView" &&
        //       (prop.state.stageName === "Redirect Review" ||
        //         prop.state.stageName === "Effectuate" ||
        //         prop.state.stageName === "Pending Effectuate" ||   
        //         prop.state.stageName === "Case Completed" ||
        //         prop.state.stageName === "CaseArchived")  
        //   }
        />
      </div>
    );
  };
  const renderSimpleDatePickerField = (name, label, index) => {
    return (
      <div className="col-xs-6 col-md-3">
        <SimpleDatePickerField
          name={name}
          label={label}
          data={gridFieldTempState}
          validationErrors={validationErrors}
          onChange={(selectValue) =>
            handleGridDateChange(
              index,
              selectValue,
              name,
              VerbalCommTable.displayName,
            )
          }
        //   disabled={
        //     prop.state.formView === "DashboardView" &&
        //       (prop.state.stageName === "Redirect Review" ||
        //         prop.state.stageName === "Effectuate" ||
        //         prop.state.stageName === "Pending Effectuate" ||   
        //         prop.state.stageName === "Case Completed" ||
        //         prop.state.stageName === "CaseArchived")  
        //   }
        />
      </div>
    );
  };

  const tdDataReplica = (index) => {
    return (
      <div className="Container AddProviderLabel AddModalLabel">
        <div className="row">
          {renderSimpleInputField("Outreach_Attempt", "Outreach Attempt", 250, index)}
          {renderSimpleDatePickerField(
              "Entry_Date_Time",
              "Entry Date Time",
              index,
          )}
           {renderSimpleSelectField(
            "Communication_Type",
            "Communication Type",
               communicationTypeValues,
            index,
          )}
           {renderSimpleSelectField(
            "Communication_With",
            "Communication With",
               communicationWithValues,
            index,
          )}
          
         
        </div>
        <div className="row mt-3">
          {renderSimpleInputField("Call_Logs", "Call Logs", 250, index)}
          {renderSimpleSelectField(
            "Purpose_of_Outreach",
            "Purpose of Outreach",
              purposeOutreachValues,
            index,
          )}
           {renderSimpleSelectField(
            "Status",
            "Status",
               statusValues,
            index,
          )}
          {renderSimpleDatePickerField(
            "Outreach_Date_Time",
            "Outreach Date Time",
            index,
          )}
        </div>
        <div className="row mt-3">

          {renderSimpleInputField("Generated_By", "Generated by", 250, index)}

        </div>
      </div>
    );
  };

  const tdData = () => {
    console.log("verbalCommGridData",verbalCommGridData)
    if (
      verbalCommGridData !== undefined &&
      verbalCommGridData.length > 0
    ) {
      return verbalCommGridData.map((data, index) => {
        return (
          <tr
            key={index}
            className={
              data.DataSource === "CredentialingApi" ? "CredentialingApi" : ""
            }
          >
            {lockStatus === "N" && (
              <>
                <td>
                  <span
                    style={{
                      display: "flex",
                    }}
                  >
                    <button
                      className="deleteBtn"
                      style={{ width: "75%", float: "left" }}
                      onClick={() => {
                        deleteTableRows(
                          index,
                          VerbalCommTable.displayName,
                          "Force Delete",
                        );
                        handleOperationValue("Force Delete");
                        decreaseDataIndex();
                      }}
                    >
                      <i className="fa fa-trash"></i>
                    </button>
                    <button
                      className="editBtn"
                      style={{ width: "75%", float: "right" }}
                      type="button"
                      onClick={() => {
                        editTableRows(
                          index,
                          VerbalCommTable.displayName,
                        );
                        handleModalChange(true);
                        handleDataIndex(index);
                        handleOperationValue("Edit");
                      }}
                    >
                      <i className="fa fa-edit"></i>
                    </button>
                  </span>
                </td>
              </>
            )}
            {lockStatus === "V" && (
              <td>
                <div>
                  <button
                    className="editBtn"
                    style={{ float: "right" }}
                    type="button"
                    onClick={() => {
                      handleModalChange(true);
                      handleDataIndex(index);
                      handleOperationValue("Edit");
                    }}
                  >
                    <i className="fa fa-eye"></i>
                  </button>
                </div>
              </td>
            )}

            {tableFields.map((e) => (
              <td className="tableData">
                {e.endsWith("_Date")
                  ? data?.[e]?.value
                    ? formatDate(data[e].value)
                    : formatDate(data[e])
                  : data?.[e]?.value
                    ? convertToCase(data[e].value)
                    : convertToCase(data[e])}
              </td>
            ))}
          </tr>
        );
      });
    }
  };

  const formatDate = (dateObj) => {
    if (dateObj) {
      if (typeof dateObj === "string") {
        dateObj = new Date(Date.parse(dateObj));
      } else if (typeof dateObj === "number") {
        dateObj = new Date(dateObj);
      }
      let dd = dateObj.getDate();
      let mm = dateObj.getMonth() + 1;
      let yyyy = dateObj.getFullYear();

      if (dd < 10) {
        dd = "0" + dd;
      }
      if (mm < 10) {
        mm = "0" + mm;
      }
      return mm + "/" + dd + "/" + yyyy;
    }
    return null;
  };

  const decreaseDataIndex = () => {
    if (operationValue === "Add" || operationValue === "Force Delete") {
      const indx = dataIndex - 1;
      setDataIndex(indx);
    }
  };

  const handleOperationValue = (oprtnValue) => {
    setOperationValue(oprtnValue);
  };

  const handleModalChange = (flag) => {
    setModalShow(flag);
  };

  const handleDataIndex = (index) => {
    setDataIndex(index);
  };

  return (
    <>
      <div className="claimTable-container">
        <table
          className="table table-bordered tableLayout"
          id="ProviderInformationTable"
        >
          <thead>
            <tr className="tableRowStyle tableHeaderColor">
              {lockStatus === "N" && (
                <th style={{ width: "" }}>
                  <button
                    className="addBtn"
                    onClick={() => {
                      addTableRows(VerbalCommTable.displayName);
                      handleModalChange(true);
                      handleDataIndex(verbalCommGridData.length);
                      handleOperationValue("Add");
                    }}
                  >
                    <i className="fa fa-plus"></i>
                  </button>
                </th>
              )}
              {lockStatus === "V" && <th style={{ width: "" }}></th>}
              {tableFields.map((e) => (
                <th scope="col">{e.replaceAll("_", " ")}</th>
              ))}
            </tr>
          </thead>
          <tbody>{tdData()}</tbody>
        </table>
      </div>
      <GridModal
        name="Documents Needed"
        validationObject={isTouched}
        modalShow={modalShow}
        handleModalChange={handleModalChange}
        dataIndex={dataIndex}
        tdDataReplica={tdDataReplica}
        deleteTableRows={deleteTableRows}
        gridName={VerbalCommTable.displayName}
        decreaseDataIndex={decreaseDataIndex}
        operationValue={operationValue}
        gridRowsFinalSubmit={gridRowsFinalSubmit}
        lockStatus={lockStatus}
        validationErrors={validationErrors}
      ></GridModal>
    </>
  );
}
